### ISSUE TITLE
The link in Section 7.a. throws an 404 error

### ISSUE THREAD

**Issue by hdiessner** [IBM/satellite-tracker#29]
7.a Build the Node-RED flow manually
Follow these instructions to Build the Node-RED flow manually. => links to a non existing page gives page not found error 404.

**Comment by scottdangelo** [comment]
I do not get a 404 error, the link is working for me, and gets me to the doc/CreateFlowManually.md file in this repository.
What to you see when you hover over the link?
When I hover, i get the link:
```
https://github.com/IBM/satellite-tracker/blob/master/doc/CreateFlowManually.md
```
Also, the name on the doc changed from CreateFlow.md 7 days ago, on July 17. I'm not sure why you might still see that link, perhaps the web page is in your cache?

**Comment by hdiessner** [comment]
https://github.com/IBM/satellite-tracker/blob/master/doc/CreateFlow.md
This change seems to be it - however, I accessed this page for the first time today, so no cache in my browser possible. Whatever github is doing here - with the link in your answer above, it does work. Thank you!
