### ISSUE TITLE
Unable to install node-red-contrib-satellites

### ISSUE THREAD

**Issue by lidderupk** [IBM/satellite-tracker#48]
I am unable to install `node-red-contrib-satellites` on node-red service provisioned on IBMCloud.

![image](https://user-images.githubusercontent.com/3187457/51448399-676b1f80-1cdb-11e9-89b3-c9595bf59ca1.png)

I am however able to install on local. My local installation is `Node-RED version: v0.19.5`. How do I check the logs on IBMCloud ? I don't see any error on Kibana logs. 

@johnwalicki

Thank you.

**Comment by johnwalicki** [comment]
@lidderupk  I have installed node-red-contrib-satellites in a Node-RED Web Starter in IBM Cloud.  I used the Node-RED Manage Palette to install the package.  I set it up many many months ago.  Ping me and I can invite you to that Node-RED / IBM Cloud instance.

**Comment by stevemar** [comment]
archiving pattern
